<?php

use Illuminate\Database\Seeder;

class TaxonomiesSeeder extends Seeder
{
    protected $dishes = [];

    /** @var $restaurant \App\Model\Restaurant */
    protected $restaurant;

    public function setRestaurant(): void
    {
        $this->restaurant = \App\Model\Restaurant::where('domain', 'demo')->first();
        if (!$this->restaurant instanceof \App\Model\Restaurant) {
            throw new InvalidArgumentException('Restaurant not was found');
        }
    }

    private function createDish(
        string $name,
        string $category,
        array $tags,
        string $image
    ) :array {
        return [
            'product' => [
                'name' => $name,
                'image_path' => "/uploads/{$image}",
                'description' => "Autogenerated description for {$name} product.",
                'price' => 0.0,
                'restaurant_id' => $this->restaurant->id
            ],
            'category' => $category,
            'tags' => $tags,
        ];
    }

    private function attachTaxonomyToProduct(
        \App\Model\Product $product,
        string $type,
        string $name
    ): void {
        $taxonomy = \App\Model\Taxonomy::where('type', $type)
            ->where('name', $name)
            ->first();

        if (!$taxonomy instanceof \App\Model\Taxonomy) {
            $taxonomy = \App\Model\Taxonomy::create([
                'name' => $name,
                'type' => $type,
                'description' => "Description for taxonomy name: {$name}, type: {$type}",
                'restaurant_id' => $this->restaurant->id
            ]);
        }

        $product->tags()->attach($taxonomy->id);
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->setRestaurant();
        $this->loadDishes();
        $this->loadSidesAndDesserts();
    }

    public function loadDishes(): void
    {
        $products = [
            $this->createDish('Bandeja paisa', 'meals', ['Comida Colombiana', 'Lunes', 'Beef'], '1.jpg'),
            $this->createDish('Chuleta valluna', 'meals', ['Comida Colombiana', 'Martes'], '2.jpg'),
            $this->createDish('Ajiaco', 'meals', ['Comida Colombiana', 'Miercoles', 'Chicken', 'Soup'], '3.jpg'),
            $this->createDish('Lomo salteado', 'meals', ['Comida Peruana', 'Jueves' ], '4.jpg'),
            $this->createDish('Pollo a la brasa', 'meals', ['Comida Chilena', 'Viernes', 'Chicken'], '5.jpg'),
            $this->createDish('Tacos al pastor', 'meals', ['Comida Mexicana', 'Sabado', 'Spicy'], '6.jpg'),
            $this->createDish('Enchiladas', 'meals', ['Comida Mexicana', 'Domingo', 'Spicy'], '7.jpg'),
        ];

        foreach ($products as $productData) {
            $product = \App\Model\Product::create($productData['product']);
            $this->attachTaxonomyToProduct($product, 'category', 'meals');

            foreach ($productData['tags'] as $tag) {
                $this->attachTaxonomyToProduct($product, 'tag', $tag);
            }
        }
    }

    public function loadSidesAndDesserts(): void
    {
        $products = [
            $this->createDish('Mango Juicy', 'juice', ['side'], '1.jpg', 'side'),
            $this->createDish('Pineapple juice', 'juice', ['side'],'1.jpg', 'side'),
            $this->createDish('Guava juice', 'juice', ['side'],'1.jpg', 'side'),
            $this->createDish('White rice', 'meals', ['side'],'1.jpg', 'side'),
            $this->createDish('French fries', 'meals', ['side'],'1.jpg', 'side'),
            $this->createDish('Rice milk', 'dessert', ['side'],'1.jpg', 'side'),
            $this->createDish('Banana split', 'dessert', ['side'],'1.jpg', 'side'),
        ];

        foreach ($products as $productData) {
            $product = \App\Model\Product::create($productData['product']);
            $this->attachTaxonomyToProduct($product, 'category', $productData['category']);

            foreach ($productData['tags'] as $tag) {
                $this->attachTaxonomyToProduct($product, 'tag', $tag);
            }
        }
    }

}
