version: '3'
services:
  web:
    tty: true
    build: .
    volumes:
      - .:/var/www/html:delegated
    environment:
      - VIRTUAL_HOST=demo.cantinapp.local
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
      - DEBUG=true
    command: >
      sh -c '
        /etc/init.d/nginx start && /etc/init.d/php7.2-fpm start
        composer install
        composer create-storage-folders
        supervisord
      '
    container_name: demo.cantinapp.local
  db:
    image: mysql:5.7
    volumes:
      - ./Docker/mysql.cnf.d/sql_mode.cnf:/etc/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "laravel"
      MYSQL_PASSWORD: "laravel"
      MYSQL_ROOT_PASSWORD: "laravel"
    depends_on:
    - web
    ports:
      - 6603:3306

networks:
  default:
    external:
      name: nginx-proxy
